language: node_js
node_js:
- node
sudo: false
script:
- npm test
deploy:
  provider: heroku
  api_key:
    secure: ZsuPkcPTotPEDDNQQdxdwNVih9jYPwVS9ETlfiM/QDKbX8UCFqCPK7P625rwcGUE+F6PDPPdapJVUunELLzd0jj9pJ6NTs+sCQMakGG/oAocp1mvllvaHB+81YiSZWrr7s4W2Yzy2Xxj37VPIYWw/enpEJOmHrUQyRd3bj5r4xaKKoeW3PCrr9X8y9CFyyFbNzw37WcH9LV8kN1KRt8Px72cxG75lldfm4sWpf4+HGAjWKQrjrRGlvZX0lBZWVGyru/ySoFen/0v+aVEqY5fIRmUkUReZL33nTqv0GBiKAleGfSt5ZuJ5nl+qEgPZP16qejBJJvPxSKuon2+wesCMMSXi/5qIgm0om8yWDdjPwmDENNprhTlJK2tdN1sQeQtYo3E0Qh/ph7MYKdL0HG9vGR3bRFyq6jjy92qXpmyu0NkxBRH0D64aY+zNiIknMAfFa0hGrgtPPb4x5XP1bfntJ5+ZIlnlc7XgIl53DOMZJNPdy4kO3yL3u+Qt7ICHbo43pyUSxPtFdrJNg/mxp2aHFcpLh5M/6HTxW91BqNteZa51MH3aDDHJdQ86o+WapzFPwV9u8W1xnWKzHB2I2vzEWPv+dMzjrLPS6qy/8uwZTAmjP1qF4l5/elMxxd/BQFEC28QjMi+PGcEa/QidgX/PepLXvTQZ3u/+v7HnyxZWvs=
  app: devopsnapratica-pipeline-01
  edge: true
